# ENVIRONMENT

export EDITOR=/usr/bin/atom
export GIT_EDITOR=/usr/bin/vim

export JAVA_HOME=/usr/bin/java
export M2_HOME=/usr/bin/mvn
export MYSQL_HOME=/usr/bin/mysql
export NVM_DIR="${HOME}/.nvm"
export REDIS_HOME=/usr/local/redis
export RVM_HOME=~/.rvm
export TOMCAT_HOME=/usr/local/tomcat
export LOCAL=~/.local
export _USR=/usr
export GPG_TTY="tty"
export DOCKERID="rafaeldev"

export PATH=${PATH}:${JAVA_HOME}/bin:${MYSQL_HOME}/bin:${REDIS_HOME}/src:${TOMCAT_HOME}/bin:${RVM_HOME}/bin:${M2_HOME}/bin:${LOCAL}/bin:${_USR}/bin

# ALIAS

alias killport='kill -9 $(lsof -i tcp:$1 -t)'
alias psx='ps aux | grep'
alias upgrade='sudo apt-get update && sudo apt-get upgrade && sudo apt-get clean'
alias work='cd ~/workspace'

## GIT

alias describe='git describe'
alias fetch='git fetch --all; git fetch --tag'
alias master='git checkout master'
alias pop='git stash pop'
alias pull='git pull'
alias push='git push && git push --tags'
alias rebase='git add -A && git stash && git pull --rebase'
alias remote='git config remote.origin.url'
alias stash='git add -A && git stash'

## RUBY

alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
alias r='bundle exec rspec'
alias rake='bundle exec rake'
alias rc='rails c'
alias rr='BROWSER=chrome_headless bundle exec rspec'
alias rs='rails s'
alias rspec='bundle exec rspec'

# # JOB
#
source ~/.job

# RVM

source ~/.rvm/scripts/rvm

# NVM

source "$NVM_DIR/nvm.sh"

# METHODS

clone() {
  git clone git@github.com:${1}/${2}
}

keygen() {
  KEY_PATH=~/.ssh/"${1}"
  EMAIL=${2}

  ssh-keygen -t rsa -b 4096 -f $KEY_PATH -C $2
  chmod 600 $KEY_PATH
  ssh-add $KEY_PATH
  cat "${KEY_PATH}.pub"
}
