alias killport='kill -9 $(lsof -i tcp:$1 -t)'
alias psx='ps aux | grep'
alias upgrade='sudo apt-get update && sudo apt-get upgrade && sudo apt-get clean'
alias work='cd ~/workspace'

## GIT

alias describe='git describe'
alias fetch='git fetch --all; git fetch --tag'
alias master='git checkout master'
alias pop='git stash pop'
alias pull='git pull'
alias push='git push && git push --tags'
alias rebase='git add -A && git stash && git pull --rebase'
alias remote='git config remote.origin.url'
alias stash='git add -A && git stash'

## RUBY

alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'
alias r='bundle exec rspec'
alias rake='bundle exec rake'
alias rc='rails c'
alias rr='BROWSER=chrome_headless bundle exec rspec'
alias rs='rails s'
alias rspec='bundle exec rspec'
